### PR TITLE
Replace C string with built-in type

### PR DESCRIPTION
**Pull request by Avimitin**
Previous implementation using `*mut i8` as C char pointer. However on Linux AArch64/ARM/RISC-V 32 & 64 platform, the C char pointer is alias to `*mut u8`. This PR replace the i8 pointer to std::ffi::c_char pointer to have cross-platform build support.

This PR also bump the build dependencies `openssl-sys` of the crate verdian-slang, which allows it to be built with OpenSSL 3.0.

### CODE REVIEW

**Comment by Avimitin** [comment]
There are still some issue in this PR. Though the library itself can be built, but slang itself can't be built on aarch64 linux platform. Old slang require x86 intrinsic and multi-platform supports are release in slang 3.0. So before verdian support slang 3.0, this PR is useless.

**Comment by vivekmalneedi** [comment]
nice catch! I see your point about upgrading slang, but this PR still fixes a bug so maybe it can be merged after a change in the title?

**Comment by Avimitin** [comment]
It is ready to be merge now :)

**Comment by vivekmalneedi** [comment]
Thanks for the fix!

**Pull request merged**
