### PR TITLE
verilator diagnostics v2

### PR DESCRIPTION
**Pull request by vivekmalneedi**
cherry picked from #176 since the original PR had conflicts with dependency updates on master

### CODE REVIEW

**Comment by vivekmalneedi** [comment]
verilator's lint output doesn't seem to be stable between versions. I can ignore the verilator test to pass CI but I think it would be confusing for a user if this only worked on specific verilator versions. I don't see a good way to use verilator as a library either.

**Comment by hakan-demirli** [comment]
I have been using [diagnostic-language-server ](https://github.com/iamcco/diagnostic-languageserver) for the last couple of months with the following regex configuration on [helix](https://github.com/helix-editor/helix) editor. I use verilator from nixpkgs which is at v 5.018.
```toml
formatPattern= [
    "^(%(Warning|Error)[^:]*:)?\\s*([^:]+):(\\d+):(\\d+)?:?\\s*(\\.\\.\\.)?\\s*(.*)$",
    {line = 4, column = 5, message= [ 7 ], security= 2}
]
```
My whole configuration is [here](https://github.com/hakan-demirli/dotfiles/blob/98ebb03a4327587d4de7ee2ce75ec58f45a583eb/.config/helix/languages.toml#L141) if it helps.

**Comment by vivekmalneedi** [comment]
Thanks @hakan-demirli, I realized verilator had an official regex in their docs so I made some slight modifications to that.

**Comment by hilbert-yaa** [comment]
Thanks for the fix @vivekmalneedi ! I haven't been working on this for a while.

**Comment by vivekmalneedi** [comment]
No problem @hilbert-yaa, thanks for contributing the original PR!

**Pull request merged**
